/*
 * Cheese actions
 */
export const FETCH_CHEESES_REQUEST = 'FETCH_CHEESES_REQUEST';
export const FETCH_CHEESES_SUCCESS = 'FETCH_CHEESES_SUCCESS';
export const FETCH_CHEESES_ERROR = 'FETCH_CHEESES_ERROR';
